name: Publish a release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  publish_archives:
    strategy:
      matrix:
        os: [macOS-latest]
        # os: [macOS-latest, windows-latest, ubuntu-18.04]

    runs-on: ${{matrix.os}}
    if: github.repository == 'nicolashaan/bipak'

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish the macOS artifacts
        if: matrix.os == 'macOS-latest'
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONARTYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONARTYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeStagingProfileId: ${{ secrets.SONARTYPE_STAGING_PROFILE_ID }}
        run: ./gradlew publishToSonatype --no-daemon
#      - name: Publish the windows artifact
#        if: matrix.os == 'windows-latest'
#        env:
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
#        run: ./gradlew publishMingwX64PublicationToMavenCentralRepository publishMingwX86PublicationToMavenCentralRepository
#      - name: Publish the linux artifact
#        if: matrix.os == 'ubuntu-18.04'
#        env:
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
#        run: ./gradlew publishLinuxX64PublicationToMavenCentralRepository

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"